### ISSUE TITLE
please delete QCS8250-FB802-chi-cdk

### ISSUE THREAD

**Issue by idealhong** [b100dian/cards#1]
dear friend:

QCS8250-FB802-chi-cdk，this project is my company's code,which was not allowed to upload to github.
it is my fault that I accidentally uploaded the repository to GitHub, which has been infringed.

It's not your fault, it's my fault. To make up for my mistake, please delete this repository. Please, please, thank you

**Comment by b100dian** [comment]
Sure.
I found your repos while searching for some error messages I have with my phone when recording videos.
I think they were for another device anyway (I dont have 8250).
Thanks for letting me know. It should be deleted now.
